### ISSUE TITLE
for imaboy321's fork - bot doesnt work at all

### ISSUE THREAD

**Issue by zytho** [olliz0r/Ledybot#4]
The bot in its current state just searches through the whole GTS for the pokemon and skips over matching trades. Maybe make it known what Dex means and a gender for all?

**Comment by imaboy321** [comment]
Sorry about that. The current release for the bot is very old. I haven't updated it with the latest in awhile.

**Comment by zytho** [comment]
All good

**Comment by zytho** [comment]
Sorry, but how does the bot even work now? The Dex number confuses me. is it the number of the deposited Pokemon or the request one? What about the gender ? Also. I think that the old way of doing things, instead of going through 3 minutes of pages before it trades is a better system.

Thanks

**Comment by imaboy321** [comment]
The point isn't to have people submit common pokemon. This method guarantees no one is skipped. The dex number is the number of the pokemon you are giving away so the pokemon they request. The gender is to specify which gender you are giving away. If you are giving away male and they are asking for female, the bot skips them because otherwise it would break.

**Comment by zytho** [comment]
thanks for clearing that up.
