### ISSUE TITLE
For imaboy321's fork. Genderless pokemon IE. Ditto, do not seem to work.

### ISSUE THREAD

**Issue by zytho** [olliz0r/Ledybot#5]
It seems to skim past whenever people request "Any" gender of pokemon too.

**Comment by imaboy321** [comment]
Doesn't for me. Genderless and any have the same index. My last giveaway was just dittos and it worked perfectly fine. Make sure you have the right dex number (132 for ditto
)

**Comment by zytho** [comment]
There is no any option? 
![ledybot_2016-12-10_13-24-41](https://cloud.githubusercontent.com/assets/10547953/21070574/0f3e852c-bedc-11e6-8ff3-d5a81443ec79.png)

**Comment by imaboy321** [comment]
Any is automatically implied. It works perfectly fine for me.

**Comment by imaboy321** [comment]
If you have a proof it is skipping please send because it is not skipping for me.

**Comment by zytho** [comment]
Just witnessed it skip past many different matching entries and traded a completely wrong match. Is this due to how far back it was in the matches or no? https://my.mixtape.moe/wpdjyh.mp4

**Comment by imaboy321** [comment]
Thank you for the video. So since NTR uses wifi streaming to send information, it might be because of a slow connection. I noticed the stream is lagging behind a lot showing that NTR doesn't have the best connection over wifi. The bot does need to be reworked to compensate this factor. I will get to work on this asap and hopefully it will fix the issue for the future.

**Comment by imaboy321** [comment]
Please test the latest version on my fork. I tested it and it works well for me. Please understand that it may look stuck or broken but it is checking the data for all the pokemon on the page. I also now have an issues section on my fork as well. If you have any more problems post there :)

**Comment by therealzef** [comment]
what version of ledybot is that? looks different from the one i'm using, and the one i'm using isn't working correctly either

**Comment by imaboy321** [comment]
https://github.com/imaboy321/Ledybot/releases/tag/v2.0b this is my latest version. The way the bot works now is that is appears broken but is actually doing all the work in the background. If there are any issues, please provide a description and pictures/video

**Comment by imaboy321** [comment]
If you watch it, it will only move to change pages. Also, when it selects the entry to trade with, it does scroll to it. It will just press A on the current one and it spoofs the game into thinking it is trading with the real entry. Just let it run for a bit and you will see :)

**Comment by therealzef** [comment]
hey, came back to say i think i got it working. this table stays completely empty though, which is why i'm unsure: https://qt.vidyagam.es/LGU8YGQ.png

what it does in detail is opens the search for a pokemon, selects ledyba, goes to the list of trainers and searches for matches
after that, it seems to just press back and then a again to open the trainer list without ever trading i think? the trainers list never gets rid of the people requesting, which is why i'm confused

**Comment by imaboy321** [comment]
It isn't going to trade because there are so many ledyba on the gts. There is technically no last page because there are so many the server starts to repeat entries early on. Use a pokemon that doesn't have many entries to start off and it will work properly.

**Comment by therealzef** [comment]
i suppose it's just something on my end, then. cause it keeps trying to send to the same person, without ever trading. https://qt.vidyagam.es/zSdtiCb.png 

thanks for trying to help though, appreciate it

**Comment by imaboy321** [comment]
Which version are you using? Update to the latest version if you haven't and then send me images of your program setup.
